tuned

diff --git a/install-scripts/ubuntu-16-04-2-amd64/preseed-install b/install-scripts/ubuntu-16-04-2-amd64/preseed-install
--- a/install-scripts/ubuntu-16-04-2-amd64/preseed-install
+++ b/install-scripts/ubuntu-16-04-2-amd64/preseed-install
@@ -31,8 +31,19 @@ UPDATE=/wisnuc/bootstrap/appifi-bootstrap-update.packed.js
 
 if [ -f $SHA1 ] || [ -f $UPDATE ]; then exit 0; fi
 
-curl -s $URL | bash - 2>&1 | tee /.wisnuc-install.log
-systemctl disable wisnuc-installer.service; fi
+curl -s $URL | bash - 2>&1 | tee /wisnuc-install.log
+
+if [ $? -eq 0 ]; then
+  systemctl disable wisnuc-installer.service; fi
+  echo "WISNUC system successfully installed."
+  echo ""
+else
+  echo "failed to install WISNUC system, please see /wisnuc-install.log for detail."
+  echo ""
+fi
+
+read -n 1 -s -p "Press any key to continue"
+echo ""
 EOF
 
 systemctl enable wisnuc-installer.service
